source 'https://rubygems.org'

gem 'rake'
gem 'cucumber'
gem 'rspec'
#gem 'page-object'
gem 'require_all'
gem 'fig_newton'
gem 'data_magic'
gem 'cucumber-rails'
gem 'capybara'
gem 'r'
gem 'nokogiri', ' 1.6.6.2'
gem 'watir-webdriver'
gem 'colorize'
#gem 'ffi', '1.9.8'
#gem 'nokogiri'
gem 'open_uri_redirections'
#gem 'open_uri'
gem 'phantomjs'
gem 'poltergeist'
gem 'watir-webdriver-performance'
gem 'multi_xml'
gem 'multi_json'
gem 'httparty'
gem 'rautomation'
gem 'execjs'
gem 'execjs-rails'
gem 'therubyracer', :platforms => :ruby
#gem 'win32-api'
#gem 'win32ole-pp'
gem 'rubysl-win32ole'
gem 'page-object'
gem 'chromedriver-installer'
gem 'poltergeist'
#gem 'csv-import'
gem 'spreadsheet'
gem 'test_helper'
gem 'webdriver-user-agent', '~> 7.2'
gem 'chromedriver-helper'
gem 'activesupport'
gem 'watir-classic'
gem 'byebug'
gem 'logger'
gem 'syntax'
gem 'cucumber_statistics'
gem 'fivemat'
gem 'capybara-user_agent'
gem 'gherkin3','~>3.1.1'
gem 'ruby-oci8'
gem 'builder'